# Generated by Django 4.1 on 2023-09-09 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("introduction", models.TextField(help_text="对作品的简要介绍")),
                ("title", models.CharField(help_text="作品的标题", max_length=100)),
                ("external_link", models.URLField(help_text="指向外部网站或资源的链接")),
                ("redirect_link", models.URLField(help_text="用于内部导航到作品详细页面的链接")),
                (
                    "image",
                    models.ImageField(
                        help_text="作品的展示图片", upload_to="portfolio_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("description", models.CharField(max_length=100)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_links",
                        to="main_page.portfolio",
                    ),
                ),
            ],
        ),
    ]
