# Generated by Django 4.1 on 2023-09-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0003_portfolio_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(
                help_text="作品的展示图片", upload_to="meida/portfolio_images/"
            ),
        ),
    ]
