# Generated by Django 4.2.6 on 2023-10-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='redirect_link',
            field=models.CharField(help_text='用于内部导航到作品详细页面的链接', max_length=255),
        ),
    ]
