# Generated by Django 4.2.6 on 2023-10-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_portfolio_redirect_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.FileField(help_text='作品的展示图片或图标', upload_to='media/portfolio_images/'),
        ),
    ]
