# Generated by Django 4.2.6 on 2023-10-06 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_portfolio_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvertedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='作品的反色图片', upload_to='media/portfolio_images/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inverted_images', to='main_page.portfolio')),
            ],
        ),
    ]
