# Generated by Django 4.2.6 on 2023-10-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_invertedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='inverted_image',
            field=models.ImageField(default=1, help_text='作品的反色展示图片', upload_to='media/portfolio_images_inverted/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InvertedImage',
        ),
    ]
