# Generated by Django 4.2.6 on 2023-10-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_portfolio_inverted_image_delete_invertedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='inverted_image',
            field=models.FileField(help_text='作品的反色展示图片', upload_to='media/portfolio_images_inverted/'),
        ),
    ]
