# Generated by Django 4.2.6 on 2023-10-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPUandGPUdatas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='score',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='score',
        ),
        migrations.AddField(
            model_name='cpu',
            name='performance_score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpu',
            name='performance_score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
