# Generated by Django 4.2.6 on 2023-10-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPUandGPUdatas', '0002_remove_cpu_score_remove_gpu_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='performance_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='performance_score',
            field=models.IntegerField(),
        ),
    ]
